[package]
name = "tapsrs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-rustls = "0.25.0"
rustls = "0.22.4"
rustls-pki-types = "1.5.0"
libc = "0.2"
log = "0.4"
env_logger = "0.10"
anyhow = "1.0"
rustls-native-certs = "0.7.0"
once_cell = "1.19.0"

[build-dependencies]
cbindgen = "0.26.0"
