[target.aarch64-apple-ios]
linker = "cc"

[target.aarch64-apple-darwin]
linker = "cc"

[target.x86_64-apple-darwin]
linker = "cc"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[target.x86_64-unknown-linux-gnu]
linker = "x86_64-linux-gnu-gcc"

[target.aarch64-pc-windows-msvc]
linker = "rust-lld"

[target.x86_64-pc-windows-msvc]
linker = "rust-lld"

[target.aarch64-linux-android]
linker = "aarch64-linux-android-clang" 